import numpy as np
from itertools import combinations
from cd import *
rng = np.random.default_rng(3)

def rand_im8():
    v = rng.standard_normal(8); v[0] = 0; return unit(v)
def pair(a, b): return np.concatenate([a, b])
def ok(label, cond): print(('PASS ' if cond else 'FAIL ') + label)

# ---------------------------------------------------------------- annihilator closed form
print('=== closed form of Ann(u + b l) in Sm ===')
good = True
for trial in range(30):
    u = rand_im8(); b = unit(rand(8, rng))
    x = pair(u, b)
    K = L('Sm', x); U, s, Vt = np.linalg.svd(K); k = nullity(K); ker = Vt[-k:].T
    # predicted: n in Im O, n ⊥ u, [b,n,u]=0 ; y = (n u, b n)
    # compute the space N = {n : n0=0, <n,u>=0, [b,n,u]=0}
    A = np.zeros((8 + 1 + 1, 8))
    for i in range(8):
        n = basis(8, i)
        A[:8, i] = assoc('O', b, n, u); A[8, i] = n[0]; A[9, i] = n @ u
    U2, s2, Vt2 = np.linalg.svd(A); kN = nullity(A); N = Vt2[-kN:].T
    Y = np.column_stack([pair(mulO(N[:, j], u), mulO(b, N[:, j])) for j in range(kN)])
    # same span?
    if not (kN == k and np.linalg.matrix_rank(np.hstack([ker, Y]), tol=1e-8) == k):
        good = False
    if not all(np.allclose(mul('Sm', x, Y[:, j]), 0, atol=1e-9) for j in range(kN)): good = False
ok('Ann(u+bl) = {nu + (bn)l : n ⊥ u imaginary, [b,n,u]=0} (30 random points)', good)
# special point
u = rand_im8(); b = np.cos(.3) * basis(8, 0) + np.sin(.3) * u
x = pair(u, b); print('  special point b in span{1,u}: ann dim', nullity(L('Sm', x)))

# ---------------------------------------------------------------- lemma: {n : [b,n,u]=0} = H(u,b)
print('=== lemma: kernel of n -> [b,n,u] is the quaternion subalgebra generated by u,b ===')
u = rand_im8(); b = unit(rand(8, rng))
A = np.column_stack([assoc('O', b, basis(8, i), u) for i in range(8)])
print('  kernel dim', nullity(A), '(expect 4)')

# ---------------------------------------------------------------- pair manifold smoothness: rank of d(mu) on every stratum
print('=== rank of d(mu)(x,y) = [R_y | L_x] at points of P (expect 16 everywhere) ===')
ranks = set()
for trial in range(200):
    u = rand_im8(); n = rand_im8(); n = unit(n - (n @ u) * u)
    t = rng.random()
    if trial % 4 == 0:   # doubly special: b = ±u
        b = u * (1 if trial % 8 else -1)
    elif trial % 4 == 1: # special: b in span{1,u}
        b = np.cos(t) * basis(8, 0) + np.sin(t) * u
    else:                # generic b in H(u,n)
        q = unit(rng.standard_normal(4)); b = q[0] * basis(8, 0) + q[1] * u + q[2] * n + q[3] * mulO(u, n)
    x = pair(u, b) / np.sqrt(2); y = pair(mulO(n, u), mulO(b, n)) / np.sqrt(2)
    assert np.allclose(mul('Sm', x, y), 0, atol=1e-9)
    ranks.add(rank(np.hstack([R('Sm', y), L('Sm', x)])))
print('  ranks found:', ranks)

# ---------------------------------------------------------------- octave swap
print('=== the 15 basis hyperplanes of F_2^4: which are composition (octonion) subalgebras? ===')
def hyperplanes():
    # nonzero linear functionals on F_2^4 ; hyperplane = kernel
    for f in range(1, 16):
        yield f, [g for g in range(16) if bin(f & g).count('1') % 2 == 0]
def is_composition(name, H):
    idx = np.array(H)
    for _ in range(20):
        x = np.zeros(16); y = np.zeros(16)
        x[idx] = rng.standard_normal(8); y[idx] = rng.standard_normal(8)
        z = mul(name, x, y)
        if not np.allclose(z[[i for i in range(16) if i not in H]], 0): return 'not closed'
        if abs(norm2(z) - norm2(x) * norm2(y)) > 1e-8: return False
    return True
tab = []
for f, H in hyperplanes():
    kind = 'V (founding octave)' if f == 8 else ('contains l' if 8 in H else 'avoids l')
    tab.append((f, H, kind, is_composition('S', H), is_composition('Sm', H)))
for f, H, kind, s, m in tab:
    print(f'  f={f:2d} H={H} [{kind:20s}]  S: {s}   Sm: {m}')
ok('S: octaves = V + the 7 hyperplanes through l', all((s == (kind != 'avoids l')) for f, H, kind, s, m in tab))
ok('Sm: octaves = the 8 hyperplanes avoiding l', all((m == (kind != 'contains l')) for f, H, kind, s, m in tab))

# ---------------------------------------------------------------- alternator kernel ("private cancellation region")
print('=== dim ker alt(x, .) = {y : (xx)y = x(xy)} for generic x ===')
for name in ['S', 'Sm']:
    ds = set()
    for _ in range(10):
        x = rand(16, rng)
        A = np.column_stack([assoc(name, x, x, basis(16, i)) for i in range(16)])
        ds.add(nullity(A))
    # also for dead x
    u = rand_im8(); b = unit(rand(8, rng)); x = pair(u, b)
    A = np.column_stack([assoc(name, x, x, basis(16, i)) for i in range(16)])
    print(f'  {name}: generic {ds}; at a dead point of Sm-type (u,b): {nullity(A)}')
# kernel of the two-sided "commutant" and associator kernels for reference
for name in ['S', 'Sm']:
    x = rand(16, rng)
    C = L(name, x) - R(name, x)
    print(f'  {name}: dim commutant of generic x: {nullity(C)}')

# ---------------------------------------------------------------- derivations
print('=== derivation algebra dimension ===')
def der_dim(name):
    T = struct(name); n = T.shape[0]
    # unknown D (n x n); equations D(e_i e_j) = D(e_i) e_j + e_i D(e_j)
    rows = []
    for i in range(n):
        for j in range(n):
            # coefficient matrix for vec(D): row index (i,j,k)
            eq = np.zeros((n, n, n))     # eq[k, p, q] coefficient of D[p,q] (D e_q = sum_p D[p,q] e_p)
            # D(e_i e_j)_k = sum_m T[i,j,m] D[k,m]
            for m in range(n):
                eq[:, :, m][np.arange(n), np.arange(n)] += T[i, j, m]
            # (D e_i) e_j = sum_p D[p,i] e_p e_j -> component k: sum_p D[p,i] T[p,j,k]
            for p in range(n):
                eq[:, p, i] -= T[p, j, :]
            # e_i (D e_j) = sum_p D[p,j] e_i e_p -> k: sum_p D[p,j] T[i,p,k]
            for p in range(n):
                eq[:, p, j] -= T[i, p, :]
            rows.append(eq.reshape(n, n * n))
    A = np.vstack(rows)
    return nullity(A)
for name in ['O', 'S', 'Sm', 'Om']:
    print(f'  Der({name}) has dimension {der_dim(name)}')
