import numpy as np
from cd import *
rng = np.random.default_rng(9)
def ok(label, cond): print(('PASS ' if cond else 'FAIL ') + label)
def rand_im8():
    v = rng.standard_normal(8); v[0] = 0; return unit(v)
def pair(a, b): return np.concatenate([a, b])

# quaternion subalgebra Q = H(e1,e2) = span{1,e1,e2,e3} ; complement Q eps with eps = e4
Q = [0, 1, 2, 3]; Qe = [4, 5, 6, 7]
def toQ(v):   # v in R^4 -> octonion in Q
    o = np.zeros(8); o[Q] = v; return o
def q_of(o): return o[Q]
def toQe(v):  # v in R^4 -> octonion v eps in Q eps  (as (0,v) in CD(Q))
    o = np.zeros(8); o[Qe] = v; return o
def mulQ(p, q): return q_of(mulO(toQ(p), toQ(q)))
def cq(v): w = -v.copy(); w[0] = v[0]; return w

a = rng.standard_normal(4); b = rng.standard_normal(4)
x = pair(toQ(a), toQ(b)); N = norm2(x)
A = np.column_stack([assoc('Sm', x, x, basis(16, i)) for i in range(16)])   # alt_x matrix
# block on M(Q): y = (c, d) with c,d in Q :  alt_x(c,d) = ([dbar b, a], b [cbar, abar])
good = True
for _ in range(10):
    c = rng.standard_normal(4); d = rng.standard_normal(4)
    y = pair(toQ(c), toQ(d)); z = A @ y
    db = mulQ(cq(d), b)
    pred1 = mulQ(db, a) - mulQ(a, db)
    pred2 = mulQ(b, mulQ(cq(c), cq(a)) - mulQ(cq(a), cq(c)))
    good &= np.allclose(z, pair(toQ(pred1), toQ(pred2)))
ok('alt_x on M(Q): alt_x(c,d) = ([d* b, a], b[c*, a*])', good)
# block on complement: alt_x(c eps, d eps) = ((d wbar) eps, (c w) eps),  w = abar b - b a
w = mulQ(cq(a), b) - mulQ(b, a)
good = True
for _ in range(10):
    c = rng.standard_normal(4); d = rng.standard_normal(4)
    y = pair(toQe(c), toQe(d)); z = A @ y
    good &= np.allclose(z, pair(toQe(mulQ(d, cq(w))), toQe(mulQ(c, w))))
ok('alt_x on M(Q)^perp: alt_x(c eps, d eps) = ((d w*) eps, (c w) eps), w = a* b - b a', good)
# w = 2(<a,b> - b0 a)
ok('w = 2(<a,b> - b0 a)', np.allclose(w, 2 * ((a @ b) * np.eye(4)[0] - b[0] * a)))
# blocks invariant
ok('L_x preserves the splitting M(Q) + M(Q)^perp', np.allclose(L('Sm', x)[np.ix_([i for i in range(16) if i % 8 >= 4], [i for i in range(16) if i % 8 < 4])], 0) and np.allclose(L('Sm', x)[np.ix_([i for i in range(16) if i % 8 < 4], [i for i in range(16) if i % 8 >= 4])], 0))
# kernel of alt_x = C_a + (b C_a) l  for generic x
a8 = toQ(a); b8 = toQ(b); ima = a8.copy(); ima[0] = 0
Ca = np.column_stack([basis(8, 0), unit(ima)])
K = np.column_stack([pair(Ca[:, 0], np.zeros(8)), pair(Ca[:, 1], np.zeros(8)), pair(np.zeros(8), mulO(b8, Ca[:, 0])), pair(np.zeros(8), mulO(b8, Ca[:, 1]))])
ok('ker alt_x = C_a + (b C_a) l  (4-dim, generic x)', nullity(A) == 4 and np.allclose(A @ K, 0, atol=1e-9))
# it is a quaternion subalgebra (composition)
comp = True
for _ in range(10):
    u_ = K @ rng.standard_normal(4); v_ = K @ rng.standard_normal(4); z = mul('Sm', u_, v_)
    comp &= np.allclose(K @ np.linalg.lstsq(K, z, rcond=None)[0], z) and abs(norm2(z) - norm2(u_) * norm2(v_)) < 1e-8
ok('the chart C_a + (b C_a) l is a composition subalgebra (= H)', comp)

# alternative elements of Sm : alt_x = 0 iff x in O or x in R + O l
def is_alt(name, x):
    A = np.column_stack([assoc(name, x, x, basis(16, i)) for i in range(16)]); return np.allclose(A, 0, atol=1e-9)
ok('Sm: l is alternative; S: l is not', is_alt('Sm', basis(16, 8)) and not is_alt('S', basis(16, 8)))
ok('Sm: (a0, b) alternative for any b', all(is_alt('Sm', pair(rng.random() * basis(8, 0), rand(8, rng))) for _ in range(5)))
ok('Sm: (a, b) with Im a != 0 and b != 0 is not alternative', not any(is_alt('Sm', pair(rand(8, rng), rand(8, rng))) for _ in range(5)))
# S: (a, b) with b in span{1, Im a} is alternative (the Dray charts)
u = rand_im8(); ok('S: (a, b) with b in span{1, Im a} is alternative', all(is_alt('S', pair(rng.random() * basis(8, 0) + rng.random() * u, rng.random() * basis(8, 0) + rng.random() * u)) for _ in range(5)))

# nucleus and centre
for name in ['S', 'Sm']:
    # left nucleus: x with [x,y,z]=0 for all y,z: linear in x
    M = np.vstack([np.column_stack([assoc(name, basis(16, i), basis(16, j), basis(16, k)) for i in range(16)]) for j in range(16) for k in range(16)])
    C = np.vstack([np.column_stack([mul(name, basis(16, i), basis(16, j)) - mul(name, basis(16, j), basis(16, i)) for i in range(16)]) for j in range(16)])
    print(f'  {name}: dim nucleus = {nullity(M)}, dim centre (commutative part) = {nullity(C)}')

# two-sidedness of annihilation in Sm
good = True
for _ in range(20):
    u = rand_im8(); b = unit(rand(8, rng)); x = pair(u, b)
    K = L('Sm', x); U, s, Vt = np.linalg.svd(K); ker = Vt[-nullity(K):]
    for y in ker:
        good &= np.allclose(mul('Sm', y, x), 0, atol=1e-9)
ok('Sm: xy = 0 implies yx = 0', good)

# subalgebra generated by a dead pair
def generated_dim(name, gens):
    B = np.array(gens, dtype=float)
    while True:
        # orthonormalize
        Uu, s, Vt = np.linalg.svd(B); r = int(np.sum(s > 1e-9)); B = Vt[:r]
        new = [mul(name, B[i], B[j]) for i in range(r) for j in range(r)]
        B2 = np.vstack([B] + new); Uu, s, Vt = np.linalg.svd(B2); r2 = int(np.sum(s > 1e-9))
        if r2 == r: return r, Vt[:r]
        B = Vt[:r2]
for name in ['S', 'Sm']:
    u = rand_im8(); n = rand_im8(); n = unit(n - (n @ u) * u)
    if name == 'S':
        x = pair(u, n)
    else:
        q = unit(rng.standard_normal(4)); b = q[0] * basis(8, 0) + q[1] * u + q[2] * n + q[3] * mulO(u, n); x = pair(u, b)
    K = L(name, x); U, s, Vt = np.linalg.svd(K); ker = Vt[-nullity(K):]; y = ker[0]
    r, B = generated_dim(name, [basis(16, 0), x, y])
    comp = all(abs(norm2(mul(name, B.T @ rng.standard_normal(r), B.T @ rng.standard_normal(r))) - 1) < 1e-8 or True for _ in range(1))
    # composition test
    cz = True
    for _ in range(10):
        p = B.T @ rng.standard_normal(r); q_ = B.T @ rng.standard_normal(r)
        cz &= abs(norm2(mul(name, p, q_)) - norm2(p) * norm2(q_)) < 1e-8
    print(f'  {name}: subalgebra generated by a dead pair (x, y) has dimension {r}; composition (octonion)? {cz}')

# M(H): (a,b) -> (a, q b) is an automorphism for unit quaternion q
q = unit(rng.standard_normal(4))
phi = lambda x: np.concatenate([x[:4], mulH(q, x[4:])])
ok('M(H): (a,b) -> (a, qb) is an automorphism', all(np.allclose(phi(mulOm(x, y)), mulOm(phi(x), phi(y))) for x, y in [(rand(8, rng), rand(8, rng)) for _ in range(5)]))
phi2 = lambda x: np.concatenate([x[:8], mulO(unit(rand(8, rng)), x[8:])])
ok("S': (a,b) -> (a, qb) is NOT an automorphism", not all(np.allclose(phi2(mulSm(x, y)), mulSm(phi2(x), phi2(y))) for x, y in [(rand(16, rng), rand(16, rng)) for _ in range(3)]))

# Bales' uniform P1^T tower (product (5,3) at every level)
mul8u = double(double(double(real_mul, 5, 3), 5, 3), 5, 3); register('U8', mul8u, 8)
mul16u = double(mul8u, 5, 3); register('U16', mul16u, 16)
comp8 = all(abs(norm2(mul8u(x, y)) - norm2(x) * norm2(y)) < 1e-8 for x, y in [(rand(8, rng), rand(8, rng)) for _ in range(5)])
print('  uniform P1^T tower: dimension-8 stage is a composition algebra?', comp8)
def der_dim(name):
    T = struct(name); n = T.shape[0]; rows = []
    for i in range(n):
        for j in range(n):
            eq = np.zeros((n, n, n))
            for m in range(n): eq[:, :, m][np.arange(n), np.arange(n)] += T[i, j, m]
            for p in range(n): eq[:, p, i] -= T[p, j, :]; eq[:, p, j] -= T[i, p, :]
            rows.append(eq.reshape(n, n * n))
    return nullity(np.vstack(rows))
print('  uniform P1^T tower: Der dims at 8 and 16:', der_dim('U8'), der_dim('U16'), ' (S\' has 14)')
# is the 8-stage isomorphic to M(H)? invariants: ann dims on (u, b)
print('  uniform 8-stage ann dims on (u imaginary, b any):', set(nullity(L('U8', pair(unit(np.r_[0, rng.standard_normal(3)]), unit(rand(4, rng))))) for _ in range(10)))

# Z(S) subset of Z(S') check and the intersection of annihilators for x in Z(S)
u = rand_im8(); n = rand_im8(); n = unit(n - (n @ u) * u); x = pair(u, n)
K1 = L('S', x); K2 = L('Sm', x)
U1, s1, V1 = np.linalg.svd(K1); U2, s2, V2 = np.linalg.svd(K2)
A1 = V1[-4:]; A2 = V2[-2:]
print('  for x in Z(S): dim Ann_S =', nullity(K1), ', dim Ann_S\' =', nullity(K2), ', dim of intersection =', 6 - np.linalg.matrix_rank(np.vstack([A1, A2]), tol=1e-8))
